'use client';
import {newId} from '@/lib/compat';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Video,Headphones,PhoneCall,PhoneOff,Clock,CheckCircle2,MessageSquare,Send,FileText,ShieldCheck,Bell,Pause,WifiOff,Tablet,ChevronLeft} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import CustomerForm from './customer-form';
import MeetCall from './meet-call';
import {meetLink} from '@/lib/meet-config';
import {useIncomingRing} from './use-incoming-ring';
import {deskRequest} from '@/lib/desk-request';
import type {Device,DeskState,Session,Prompt} from '@/lib/contracts';
type Action={action:string;[key:string]:unknown};
export default function Desk({device,startOnMount=false,initialAudio=null}:{device:Device;startOnMount?:boolean;initialAudio?:AudioContext|null}){
 const [state,setState]=useState<DeskState|null>(null),[error,setError]=useState(''),[network,setNetwork]=useState(false),[lastOk,setLastOk]=useState<number|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(device.role==='staff'),[done,setDone]=useState(false),[message,setMessage]=useState(''),[notice,setNotice]=useState('');
 const readyRef=useRef(device.role==='staff'),connection=useRef<string|null>(null),request=useRef(0),lastActive=useRef<string|null>(null),requestId=useRef<string|null>(null),busyRef=useRef(false),live=useRef(true);
 const isStaff=device.role==='staff';const mine=state?.sessions.find(s=>isStaff?s.staff===device.slot:s.store===device.slot),queue=state?.sessions.filter(s=>s.status==='waiting')??[];
 const ring=useIncomingRing(isStaff&&ready&&!mine&&queue.length>0&&!network,initialAudio);
 const fetchState=useCallback(async()=>{const seq=++request.current;try{const data=await deskRequest<DeskState>('/api/desk?role='+device.role+'&slot='+device.slot);if(seq===request.current&&live.current){setState(data);setNetwork(false);setLastOk(Date.now());const active=data.sessions.find((s:Session)=>device.role==='staff'?s.staff===device.slot:s.store===device.slot);if(lastActive.current&&!active){setDone(true);requestId.current=null;setMessage('');}lastActive.current=active?.id??null;}return data;}catch(e){if(seq===request.current&&live.current){setNetwork(true);}return null;}},[device.role,device.slot]);
 const send=useCallback((a:Action)=>{try{connection.current??=newId();}catch{connection.current=null;}return deskRequest<any>('/api/desk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,device,...(a.action==='heartbeat'&&connection.current?{clientId:connection.current}:{})})},20000)},[device.role,device.slot]);
 async function run(a:Action){if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{const r=await send(a);if(a.action==='end'){setState(old=>old?{...old,sessions:old.sessions.filter(s=>s.id!==a.id)}:old);lastActive.current=null;requestId.current=null;setMessage('');setDone(true);setNotice('受付を終了しました。双方でGoogle Meetから退出したことをご確認ください。');}await fetchState();return true;}catch(e){setError(e instanceof Error?e.message:'送信に失敗しました。再試行してください。');await fetchState();return false;}finally{busyRef.current=false;setBusy(false);}}
 useEffect(()=>{live.current=true;let timer:ReturnType<typeof setTimeout>;let stop=false;async function loop(){await fetchState();if(!stop)timer=setTimeout(loop,2000)}void loop();return()=>{stop=true;live.current=false;clearTimeout(timer)}},[fetchState]);
 useEffect(()=>{if(!isStaff)return;
  // Each open receiver reports its own connection; one tab cannot pause another.
  const pulse=()=>send({action:'heartbeat',ready:readyRef.current&&document.visibilityState==='visible'}).catch(()=>{});
  const changed=()=>{void pulse();if(document.visibilityState==='visible')void fetchState();};
  void pulse();const timer=setInterval(pulse,15000);document.addEventListener('visibilitychange',changed);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',changed);void send({action:'heartbeat',ready:false}).catch(()=>{})}
 },[isStaff,send,fetchState]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();Promise.resolve(context.registerTool({name:'read_support_desk',title:'受付状況を確認',description:'現在の画面と同じ受付状況を取得します。顧客入力内容は返しません。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('引数は空のオブジェクトです');const d=await fetchState();if(!d)throw new Error('接続できません');return {waiting:d.sessions.filter((s:Session)=>s.status==='waiting').length,sessions:d.sessions.map((s:Session)=>({store:s.store,status:s.status,staff:s.staff}))};}},{signal:c.signal})).catch(()=>{});return()=>c.abort();},[fetchState]);
 async function enableSound(){try{await ring.arm();setNotice('着信音を有効にしました。');}catch{setNotice('着信音を有効にできませんでした。着信の表示と応答は利用できます。');}}
 async function toggle(){const next=!ready;readyRef.current=next;setReady(next);if(next)void enableSound();try{await send({action:'heartbeat',ready:next});setError('');await fetchState();}catch(e){setError(e instanceof Error?e.message:'受付状態を変更できませんでした')}}
 const started=useRef(false);
 useEffect(()=>{if(!startOnMount||started.current)return;started.current=true;if(!isStaff){requestId.current??=newId();void run({action:'call',requestId:requestId.current});}},[startOnMount]);
 async function startMeet(a:Action,store:string){
  if(busyRef.current)return;
  const url=meetLink(store);if(!url){setError('この店舗の会議リンクは未設定です。端末設定でテスト店舗Aを選んでください。');return;}
  // Start the request before reserving a window; heartbeat pauses while it runs.
  const accepted=run(a);
  let popup:Window|null=null;
  try{popup=window.open('about:blank','_blank');if(popup){popup.opener=null;popup.document.title='Google Meetを準備しています';popup.document.body.textContent='受付を確認しています。少しお待ちください。';}}catch{}
  const ok=await accepted;
  if(!ok){try{popup?.close();}catch{}return;}
  if(popup&&!popup.closed){try{popup.location.replace(url);return;}catch{try{popup.close();}catch{}}}
  setNotice('Meetを自動で開けませんでした。この画面の「Google Meetを開く」を押してください。');
 }
 const available=state?.available??0;
 return <main className={'desk '+(isStaff?'staff-desk':'store-desk')}><header className="desk-header"><div className="brand"><span className="brandmark"><Video size={23}/></span><span>ALLMIGHTY <b>Connect</b></span></div><div className="device-name">{isStaff?<Headphones size={18}/>:<Tablet size={18}/>} {isStaff?'三宮 / '+(device.slot==='5'?'業務端末':'iPad '+device.slot):'三宮を呼び出す窓口'}</div></header>
 <div className="pilot-strip"><span>受信接続版 10/2b · 架空の情報でお試しください</span><a href={"/settings/"+device.role}>端末設定</a></div>
 <div className="connection-line" aria-live="polite">{state?.account?<span>ログイン: <b>{state.account}</b>（呼び出し側と受付側で同じアカウントが必要です）</span>:<span>ログインを確認しています</span>}<span>{network?'接続エラー':lastOk?'接続OK '+new Date(lastOk).toLocaleTimeString('ja-JP'):'接続中'}{isStaff&&state?' · 受付中の端末 '+state.staff.filter(p=>p.ready&&p.seen>state.now-45000).map(p=>p.slot).join(','):''}</span></div>
 {network&&<div className="error-banner" role="alert"><WifiOff/>接続を確認しています。画面の内容は最新でない可能性があります。</div>}{error&&<div className="error-banner" role="alert"><span>{error}</span><Button variant="outline" onClick={()=>{setError('');void fetchState()}}>再確認</Button></div>}{notice&&<div className="info-banner" role="status">{notice}</div>}
 {!state&&!network&&<div className="center-stage"><Clock/><h2>受付を準備しています</h2></div>}
 {state&&isStaff&&!mine&&<section className="customer-welcome"><div className={'welcome-icon '+(queue.length?'ringing':'')}><Headphones size={46}/></div><p className="eyebrow">三宮の受付 · 受信用</p><h1 aria-live="polite">{queue.length?'店舗から呼び出しです':ready?'着信をお待ちしています':'受付を休止しています'}</h1><p>{queue.length?'下のボタンで、この端末から応答できます。':ready?'店舗の呼び出しを受信しています。この画面を開いたままお待ちください。':'受付を再開すると、着信音を鳴らしてお知らせします。'}</p>{queue.length?<Button className="call-button" disabled={busy||network} onClick={()=>{setDone(false);void startMeet({action:'claim',id:queue[0].id},queue[0].store)}}><PhoneCall size={30}/>{busy?'接続しています…':'応答する'}</Button>:!ready?<Button className="call-button" disabled={busy||network} onClick={toggle}><Bell size={30}/>受付を再開する</Button>:!ring.audioReady?<Button className="call-button" disabled={busy||network} onClick={()=>void enableSound()}><Bell size={30}/>着信音を有効にする</Button>:<div className="waiting-label"><Bell size={24}/>受付中 · 着信音は有効です</div>}<p className="small-note">{network?'受付との通信を再接続しています。':queue.length?'着信を受信しました。応答するとGoogle Meetが開きます。':!ring.audioReady?'画面への着信は受信できます。音を鳴らすには一度ボタンを押してください。':'受信接続中です。画面のロック中や別アプリの使用中は着信を受けられないことがあります。'}</p><details className="device-settings"><summary>受付の設定</summary><Button variant="outline" onClick={toggle}>{ready?'受付を休止する':'受付を再開する'}</Button><Button variant="outline" onClick={()=>{void ring.test().catch(()=>setNotice('音量とブラウザの設定をご確認ください。'))}}>着信音を確認</Button></details></section>}
 {state&&!isStaff&&!mine&&<section className="customer-welcome"><div className="welcome-icon">{done?<CheckCircle2 size={46}/>:<Headphones size={46}/>}</div><p className="eyebrow">オールマイティ 遠隔サポート</p><h1>{done?'ご相談ありがとうございました':'お困りごとを、\nスタッフに相談できます。'}</h1><p>{done?'入力内容を消去しました。次のお客様もこの画面からご利用いただけます。':'パソコンの設定やアカウントのこと。三宮のスタッフが、画面越しにご案内します。'}</p><Button className="call-button" disabled={busy||network} onClick={()=>{setDone(false);requestId.current??=newId();void startMeet({action:'call',requestId:requestId.current},device.slot)}}><PhoneCall size={30}/>{busy?'呼び出しています…':'三宮を呼び出す'}</Button><div className="availability">{available?'三宮で受付中です':'受付可能なスタッフを確認中です。呼び出し後、そのままお待ちいただけます。'}</div><div className="welcome-note"><ShieldCheck size={18}/>呼び出すとGoogle Meetが開きます。「参加」を押してお待ちください。カメラ・マイクの初回許可が必要です。</div></section>}
 {mine?.status==='waiting'&&!isStaff&&<section className="customer-welcome"><div className="welcome-icon ringing"><PhoneCall size={44}/></div><p className="eyebrow">店舗 {device.slot} から呼び出し中</p><h1>三宮のスタッフを<br/>呼び出しています</h1><p>{available?'スタッフが応答するまで、少しお待ちください。':'ただいま受付できるスタッフがいません。そのままお待ちいただくか、時間をおいてお試しください。'}</p>{(state?.queuePosition??1)>1&&<div className="waiting-label"><Clock size={20}/>別の店舗もお待ちです。順番にご案内します。</div>}<MeetCall store={mine.store} waiting/><Button variant="outline" className="large-button" disabled={busy} onClick={()=>run({action:'end',id:mine.id,outcome:'cancelled'})}>呼び出しを取り消す</Button></section>}
 {mine?.status==='active'&&<><div className="session-heading"><span><Headphones size={18}/>{isStaff?'店舗 '+mine.store+' のお客様':'三宮 受付 '+mine.staff+' がご案内します'}</span><EndButton busy={busy} staff={isStaff} onEnd={()=>run({action:'end',id:mine.id,outcome:isStaff?'completed':'cancelled'})}/></div><div className="consultation-grid"><div className="conversation-column"><MeetCall store={mine.store}/><section className="messages panel"><h3><MessageSquare size={18}/> メッセージ</h3><div className="message-log" aria-live="polite">{mine.messages.length?mine.messages.map(m=><div className={'message '+(m.role===device.role?'own':'')} key={m.id}><small>{m.role==='staff'?'三宮スタッフ':'お客様'}</small><p>{m.text}</p></div>):<p className="small-note">聞き取りにくいときは、文字でもお伝えできます。</p>}</div>{!isStaff&&<div className="quick-messages">{['料金を知りたいです','もう一度説明してください','音が聞こえません'].map(t=><Button key={t} variant="outline" disabled={busy} onClick={()=>run({action:'message',id:mine.id,text:t})}>{t}</Button>)}</div>}<form className="message-compose" onSubmit={async e=>{e.preventDefault();if(await run({action:'message',id:mine.id,text:message}))setMessage('')}}><Input value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} required aria-label="メッセージ" placeholder="パスワードや認証コードは送らないでください" autoComplete="off"/><Button type="submit" disabled={busy||!message.trim()} aria-label="メッセージを送信"><Send size={18}/></Button></form></section></div><section className="workflow-panel panel">{isStaff?<StaffWorkflow session={mine} busy={busy} run={run}/>:mine.prompt?<CustomerForm key={mine.prompt.id} prompt={mine.prompt} busy={busy} onSubmit={answer=>run({action:'answer',id:mine.id,promptId:mine.prompt!.id,answer})}/>:<div className="form-empty"><FileText size={40}/><h2>スタッフがご案内します</h2><p>入力が必要になったら、ここに画面が表示されます。Meetのタブからこの受付画面へ戻ってご確認ください。</p></div>}</section></div></>}
 <footer><span>オールマイティ Connect</span><span>検証版 · 終了時に入力内容を消去</span></footer></main>
}
function EndButton({busy,staff,onEnd}:{busy:boolean;staff:boolean;onEnd:()=>Promise<boolean>}){return <AlertDialog><AlertDialogTrigger asChild><Button variant="outline" className="end-button" disabled={busy}><PhoneOff size={17}/>相談を終了</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>この相談を終了しますか？</AlertDialogTitle><AlertDialogDescription>先に双方でGoogle Meetから退出してください。この操作は入力内容とメッセージを消去して受付画面に戻します。Meetの通話を自動では終了しません。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>相談を続ける</AlertDialogCancel><AlertDialogAction onClick={()=>void onEnd()}>終了して内容を消去</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
function StaffWorkflow({session:s,busy,run}:{session:Session;busy:boolean;run:(a:Action)=>Promise<boolean>}){
 const [kind,setKind]=useState<Prompt['kind']>('contact'),[text,setText]=useState(''),[price,setPrice]=useState('');const waiting=!!s.prompt&&!s.prompt.answeredAt;const labels:Record<string,string>={name:'お名前',topic:'ご相談内容',consent:'送信への同意',account:'アカウント',emailPlan:'メールのご希望',ownDevice:'作成に使う端末',decision:'お客様の回答'};
 return <><p className="eyebrow">お客様の画面を案内</p><h2>入力・確認を送る</h2>{s.prompt&&<div className={'received-card '+(waiting?'pending':'')}><strong>{waiting?'お客様の入力を待っています':'回答を受け取りました'}</strong><p>{s.prompt.title}</p>{s.prompt.answer&&<dl>{Object.entries(s.prompt.answer).map(([k,v])=><div key={k}><dt>{labels[k]??k}</dt><dd>{v==='yes'?'同意済み':v}</dd></div>)}</dl>}</div>}
 <div className="template-grid" role="group" aria-label="送信する画面">{([['contact','ご相談内容'],['microsoft','Microsoftの準備'],['offer','サービス・料金'],['guide','案内を送る']] as const).map(([k,label])=><Button variant={kind===k?'default':'outline'} key={k} aria-pressed={kind===k} disabled={waiting||busy} onClick={()=>{setKind(k);setText('');setPrice('')}}>{label}</Button>)}</div>
 {kind==='contact'&&<p className="template-description">お名前と相談内容をお客様に入力していただきます。検証中は仮名を使用してください。</p>}
 {kind==='microsoft'&&<div className="template-description"><p>アカウントの有無・メールの希望・お客様の端末を確認します。</p><p className="safety-note">作成はお客様自身の端末でご案内します。パスワードや認証コードは受け取りません。</p></div>}
 {(kind==='offer'||kind==='guide')&&<label className="input-label">{kind==='offer'?'サービス内容・作業範囲':'お客様に表示する案内'}<Textarea value={text} onChange={e=>setText(e.target.value)} maxLength={1200} rows={4} disabled={waiting} placeholder={kind==='offer'?'例：パソコン初期設定。作業内容と対象外の内容を記載してください。':'例：お客様ご自身のパソコンで、Microsoftのアカウント作成画面を開いてください。'}/></label>}
 {kind==='offer'&&<label className="input-label">税込料金（円）<Input type="number" min="0" max="10000000" value={price} onChange={e=>setPrice(e.target.value)} inputMode="numeric" disabled={waiting} placeholder="正式な料金を入力"/><small>内容の確認用です。決済・正式な契約締結は行いません。</small></label>}
 <Button className="large-button full" disabled={busy||waiting||((kind==='guide'||kind==='offer')&&!text.trim())||(kind==='offer'&&price==='')} onClick={async()=>{if(await run({action:'sendPrompt',id:s.id,kind,text,...(kind==='offer'?{price:Number(price)}:{})})){setText('');setPrice('')}}}><Send size={18}/>{waiting?'お客様の回答待ち':'お客様の画面に表示する'}</Button><p className="small-note">次の画面を送ると、前の回答の表示は置き換わります。</p></>
}


