import {meetLink} from '@/lib/meet-config';
import {actionSchema,deviceSchema,validateAnswer,type Session} from '@/lib/contracts';
import {alertReceivers} from '@/lib/alerts';
import {vapidKeys} from '@/lib/webpush';
import {db,identity,account,originCheck,roleCheck,clean,session,decode,participant,save,reply,fail,ApiError} from '@/lib/server';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const user=await account();const tenant=user.userId;const q=new URL(req.url).searchParams;const d=deviceSchema.parse({role:q.get('role'),slot:q.get('slot')});await clean(tenant);const rows=d.role==='staff'?await db().prepare("SELECT * FROM consultations WHERE tenant=? AND status!='ended' ORDER BY created").bind(tenant).all():await db().prepare("SELECT * FROM consultations WHERE tenant=? AND store=? AND status!='ended' ORDER BY created").bind(tenant,d.slot).all();const staff=await db().prepare('SELECT slot,MAX(CASE WHEN ready=1 AND seen>? THEN 1 ELSE 0 END) AS ready,MAX(seen) AS seen FROM (SELECT slot,ready,seen FROM presence WHERE tenant=? UNION ALL SELECT slot,ready,seen FROM receiver_connections WHERE tenant=?) GROUP BY slot').bind(Date.now()-45000,tenant,tenant).all();const all=(await db().prepare("SELECT store,staff,status,created FROM consultations WHERE tenant=? AND status!='ended' ORDER BY created").bind(tenant).all()).results as any[];const available=(staff.results as any[]).filter(p=>p.ready&&p.seen>Date.now()-45000&&!all.some(s=>s.staff===p.slot&&s.status==='active')).length;const queuePosition=all.filter(s=>s.status==='waiting').findIndex(s=>s.store===d.slot)+1;let pushPublicKey:string|undefined;if(d.role==='staff'){try{pushPublicKey=(await vapidKeys()).publicKey;}catch{pushPublicKey=undefined;}}else{const waiting=rows.results.map(decode).find(s=>s.status==='waiting');if(waiting){try{await alertReceivers(tenant,waiting,new URL(req.url).origin);}catch{}}}return reply({account:user.email,pushPublicKey,available,queuePosition,sessions:rows.results.map(decode).map(s=>d.role==='staff'&&s.staff!==d.slot?{...s,prompt:null,messages:[]}:s),staff:staff.results,videoConfigured:!!meetLink(d.role==='store'?d.slot:'A'),now:Date.now()});}catch(e){return fail(e)}}
export async function POST(req:Request){try{originCheck(req);const tenant=await identity();const rawText=await req.text();if(rawText.length>8000)throw new ApiError(413,'送信内容が長すぎます。');let raw:any;try{raw=JSON.parse(rawText)}catch{throw new ApiError(400,'入力形式が不正です。')}const d=deviceSchema.parse(raw.device);const a=actionSchema.parse(raw);await clean(tenant);
 if(a.action==='subscribe'){roleCheck(d,'staff');await db().prepare('INSERT INTO push_subscriptions(endpoint,tenant,slot,p256dh,auth,client,created) VALUES(?,?,?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET tenant=excluded.tenant,slot=excluded.slot,p256dh=excluded.p256dh,auth=excluded.auth').bind(a.subscription.endpoint,tenant,d.slot,a.subscription.keys.p256dh,a.subscription.keys.auth,null,Date.now()).run();return reply({ok:true});}
 if(a.action==='unsubscribe'){roleCheck(d,'staff');await db().prepare('DELETE FROM push_subscriptions WHERE endpoint=? AND tenant=?').bind(a.endpoint,tenant).run();return reply({ok:true});}
 if(a.action==='heartbeat'){roleCheck(d,'staff');if(a.clientId){await db().prepare('INSERT INTO receiver_connections(tenant,slot,client,ready,seen) VALUES(?,?,?,?,?) ON CONFLICT(tenant,slot,client) DO UPDATE SET ready=excluded.ready,seen=excluded.seen').bind(tenant,d.slot,a.clientId,a.ready?1:0,Date.now()).run();}else{await db().prepare('INSERT INTO presence(tenant,slot,ready,seen) VALUES(?,?,?,?) ON CONFLICT(tenant,slot) DO UPDATE SET ready=excluded.ready,seen=excluded.seen').bind(tenant,d.slot,a.ready?1:0,Date.now()).run();}return reply({ok:true});}
 if(a.action==='call'){roleCheck(d,'store');if(!meetLink(d.slot))throw new ApiError(503,'この店舗のGoogle Meet会議リンクは未設定です。端末設定をご確認ください。');const previous=await db().prepare("SELECT * FROM consultations WHERE tenant=? AND store=? AND status!='ended'").bind(tenant,d.slot).first<any>();if(previous)return reply({id:previous.id});const now=Date.now();await db().prepare("INSERT OR IGNORE INTO consultations(id,tenant,store,staff,status,created,expires,version,payload) VALUES(?,?,?,NULL,'waiting',?,?,0,?)").bind(a.requestId,tenant,d.slot,now,now+2*60*60*1000,JSON.stringify({prompt:null,messages:[]})).run();const created=await db().prepare("SELECT id FROM consultations WHERE tenant=? AND store=? AND status!='ended'").bind(tenant,d.slot).first<any>();if(!created)throw new ApiError(409,'呼び出しをもう一度やり直してください。');try{await alertReceivers(tenant,await session(tenant,created.id),new URL(req.url).origin);}catch{}return reply({id:created.id});}
 const s=await session(tenant,a.id);
 if(a.action==='claim'){roleCheck(d,'staff');// Receiving and answering do not depend on permission to play sound.
 let r;try{r=await db().prepare("UPDATE consultations SET staff=?,status='active',version=version+1 WHERE tenant=? AND id=? AND status='waiting'").bind(d.slot,tenant,s.id).run();}catch{throw new ApiError(409,'すでに別の相談を対応中です。')}if(!r.meta.changes)throw new ApiError(409,'他のスタッフが応答しました。');return reply({ok:true});}
 participant(s,d);if(s.status==='ended')throw new ApiError(409,'この相談は終了しました。');
 if(a.action==='end'){if(s.status==='waiting'&&d.role!=='store')throw new ApiError(403,'取り消せません。');s.status='ended';s.prompt=null;s.messages=[];s.outcome=a.outcome;await save(tenant,s);return reply({ok:true,videoClosed:false});}
 if(s.status!=='active')throw new ApiError(409,'スタッフの応答をお待ちください。');
 if(a.action==='video'){const url=meetLink(s.store);if(!url)throw new ApiError(503,'この店舗の会議リンクは未設定です。');return reply({provider:'google-meet',url});}
 if(a.action==='sendPrompt'){roleCheck(d,'staff');if(s.prompt&&!s.prompt.answeredAt)throw new ApiError(409,'お客様が回答するまで次の画面は送れません。');if(a.kind==='offer'&&(!a.text||a.price===undefined))throw new ApiError(400,'サービス内容と税込料金を入力してください。');if(a.kind==='guide'&&!a.text)throw new ApiError(400,'案内文を入力してください。');const titles={contact:'ご相談について教えてください',microsoft:'Microsoftアカウントの準備',offer:'サービス内容のご確認',guide:'スタッフからのご案内'};s.prompt={id:crypto.randomUUID(),kind:a.kind,title:titles[a.kind],text:a.text,price:a.price};await save(tenant,s);return reply({ok:true});}
 if(a.action==='answer'){roleCheck(d,'store');if(!s.prompt||s.prompt.id!==a.promptId||s.prompt.answeredAt)throw new ApiError(409,'この入力画面は更新されたか、すでに送信済みです。');s.prompt.answer=validateAnswer(s.prompt,a.answer);s.prompt.answeredAt=Date.now();await save(tenant,s);return reply({ok:true});}
 if(a.action==='message'){s.messages=[...s.messages,{id:crypto.randomUUID(),role:d.role,text:a.text,at:Date.now()}].slice(-20);await save(tenant,s);return reply({ok:true});}
 return reply({error:'未対応の操作です。'},400);
 }catch(e){return fail(e)}}

